### ISSUE TITLE
VCF as input?

### ISSUE THREAD

**Issue by ammaraziz** [alexdonath/gappy2#1]
Hi,

Do you think a VCF containing indels could be used as input for gappy? I realise currently it's not setup for vcf parsing but it would be amazing if a VCF file can be used to generate splids.

**Comment by alexdonath** [comment]
Hi,

Support for VCF files is currently not planned. Have you tried converting the file in another format such as MAF?

a

**Comment by ammaraziz** [comment]
Hi Alex,

I'll look in MAF, it's a new file format that I haven't used before!

**Comment by alexdonath** [comment]
Just make sure that you are looking at the Multiple Alignment Format, _not_ the Mutation Annotation Format. The former is a multiple sequence alignment format, the latter is more related to VCF.

a
